import React, { createContext, useContext, useState, ReactNode } from 'react'

export type Language = 'de' | 'en' | 'fr' | 'it' | 'es' | 'el' | 'tr' | 'zh' | 'ja' | 'ru' | 'pt' | 'hi' | 'ar'

interface LanguageContextType {
  currentLanguage: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

interface LanguageProviderProps {
  children: ReactNode
}

// Translation keys and values
const translations = {
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.quiz': 'Quiz',
    'nav.leaderboard': 'Bestenliste',
    'nav.profile': 'Profil',
    'nav.minigames': 'Minispiele',
    'nav.events': 'Events',
    'nav.speedrun': 'Speedrun Media',
    'nav.collector': 'Sammler Modus',
    'nav.forum': 'Forum',
    'nav.classic': 'Klassisch',
    'nav.marketplace': 'Marktplatz',
    'nav.friends': 'Freunde',
    'nav.fanart': 'Fanart',
    'nav.news': 'News',
    'nav.media': 'Media',
    'nav.community': 'Community',
    
    // Home Screen
    'home.subtitle': 'Die N64-Community für Millennials',
    'home.welcome': 'Willkommen zurück',
    'home.quiz.subtitle': 'N64 Wissen',
    'home.events.subtitle': 'Turniere',
    'home.media.subtitle': 'Speedruns',
    'home.collector.subtitle': 'Kollektion',
    'home.forum.subtitle': 'Community',
    'home.profile.subtitle': 'Mein Account',
    'home.leaderboard.subtitle': 'Top Spieler',
    'home.minigames.subtitle': 'Spaß',
    'home.marketplace.subtitle': 'Handel',
    'home.friends.subtitle': 'Soziales Netzwerk',
    'home.fanart.subtitle': 'Kreativität',
    'home.news.subtitle': 'Updates',
    'home.classic.subtitle': 'Retro-Erlebnis',
    'home.footer.retro': 'Retro neu entfacht',
    'home.footer.n64': 'Für die N64-Generation',
    'home.footer.classic': 'Zur klassischen Ansicht mit News Feed',
    'home.footer.tagline': 'Battle64 - Wo Nostalgie auf Community trifft',
    'home.newsfeed': 'News Feed',
    'home.liveEvents': 'Live Events',
    'home.noEventsActive': 'Keine aktiven Events',
    'home.noTimesSubmitted': 'Noch keine Zeiten eingereicht',
    'home.beTheFirst': 'Sei der Erste!',
    'home.topLeaderboard': 'Top 3 Leaderboard:',
    'home.winner': 'Gewinner',
    'home.verified': 'Verifiziert',
    'home.participants': 'Teilnehmer',
    'home.timeRemaining': 'Zeit verbleibend',
    'home.ended': 'Beendet',
    'home.screenshot': 'Screenshot',
    'home.video': 'Video (Dauerschleife)',
    'home.livestream': 'Livestream',
    'home.livestreamProof': 'Livestream Beweis',
    'home.noMediaAvailable': 'Kein Media verfügbar',
    'home.showMoreNews': 'weitere News anzeigen',
    
    // Common
    'common.welcome': 'Willkommen',
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.submit': 'Absenden',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Vorherige',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.sort': 'Sortieren',
    'common.close': 'Schließen',
    'common.play': 'Spielen',
    'common.pause': 'Pausieren',
    'common.refresh': 'Aktualisieren',
    'common.details': 'Details',
    'common.viewAll': 'Alle anzeigen',
    'common.noData': 'Keine Daten verfügbar',
    'common.confirm': 'Bestätigen',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.ok': 'OK',
    'common.retry': 'Wiederholen',
    
    // Authentication
    'auth.login': 'Anmelden',
    'auth.logout': 'Abmelden',
    'auth.register': 'Registrieren',
    'auth.username': 'Benutzername',
    'auth.password': 'Passwort',
    'auth.email': 'E-Mail',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.loginRequired': 'Anmeldung erforderlich',
    'auth.loginRequiredMessage': 'Du musst angemeldet sein, um diese Seite zu sehen.',
    'auth.loginRequiredForEvents': 'Bitte logge dich ein, um an Events teilzunehmen!',
    
    // Quiz
    'quiz.title': 'N64 Quiz',
    'quiz.start': 'Quiz starten',
    'quiz.question': 'Frage',
    'quiz.score': 'Punkte',
    'quiz.timeLeft': 'Zeit übrig',
    'quiz.correct': 'Richtig!',
    'quiz.incorrect': 'Falsch!',
    'quiz.finished': 'Quiz beendet',
    'quiz.results': 'Ergebnisse',
    'quiz.testYourKnowledge': 'Teste dein N64-Wissen!',
    'quiz.difficulty': 'Schwierigkeit',
    'quiz.category': 'Kategorie',
    'quiz.restart': 'Neu starten',
    'quiz.wrong': 'Falsch!',
    
    // Profile
    'profile.title': 'Profil',
    'profile.username': 'Benutzername',
    'profile.email': 'E-Mail',
    'profile.level': 'Level',
    'profile.experience': 'Erfahrung',
    'profile.achievements': 'Erfolge',
    'profile.statistics': 'Statistiken',
    'profile.points': 'Punkte',
    'profile.badges': 'Abzeichen',
    'profile.stats': 'Statistiken',
    'profile.games': 'Spiele',
    'profile.completed': 'Abgeschlossen',
    'profile.favorites': 'Favoriten',
    'profile.edit': 'Profil bearbeiten',
    'profile.settings': 'Einstellungen',
    'profile.overview': 'Übersicht',
    'profile.collection': 'Sammlung',
    'profile.records': 'Rekorde',
    'profile.joinDate': 'Dabei seit',
    'profile.editProfile': 'Profil bearbeiten',
    'profile.personalBest': 'Persönliche Bestzeit',
    'profile.completions': 'Abschlüsse',
    'profile.bestTime': 'Beste Zeit',
    'profile.highScore': 'Höchste Punktzahl',
    'profile.achievedOn': 'Erreicht am',
    
    // Events
    'events.title': 'Events',
    'events.upcoming': 'Kommende Events',
    'events.active': 'Aktive Events',
    'events.completed': 'Abgeschlossene Events',
    'events.participate': 'Teilnehmen',
    'events.details': 'Details',
    'events.noActive': 'Keine aktiven Events',
    'events.viewAll': 'Alle Events anzeigen',
    'events.joinEvent': 'Event beitreten',
    'events.leaveEvent': 'Event verlassen',
    'events.submitTime': 'Zeit einreichen',
    'events.viewLeaderboard': 'Bestenliste anzeigen',
    'events.participants': 'Teilnehmer',
    'events.timeRemaining': 'Verbleibende Zeit',
    'events.ended': 'Beendet',
    'events.notStarted': 'Noch nicht gestartet',
    'events.raceTime': 'Rennzeit',
    'events.documentation': 'Nachweis',
    'events.mediaUrl': 'Media URL',
    'events.livestreamUrl': 'Livestream URL',
    'events.notes': 'Notizen',
    'events.submissionSuccess': 'Zeit erfolgreich eingereicht!',
    'events.joinSuccess': 'Erfolgreich zum Event angemeldet! Du kannst jetzt deine Zeit einreichen.',
    'events.timeFormat': 'Format: MM:SS.mmm (z.B. 1:32.456)',
    'events.mediaFormatHelp': 'Akzeptierte Formate: JPG, PNG, MP4, WebM',
    'events.livestreamFormatHelp': 'Link zu deinem Twitch- oder YouTube-Stream',
    'events.notesPlaceholder': 'Setup, Controller, besondere Umstände...',
    'events.mediaUrlPlaceholder': 'https://twitch.tv/dein-kanal oder https://youtube.com/watch?v=...',
    'events.raceSubmission': 'Zeit Einreichen',
    'events.eventTitle': 'Event Titel',
    'events.selectDocumentation': 'Nachweis auswählen',
    'events.photo': 'Foto',
    'events.photoDesc': 'Screenshot des Endergebnisses',
    'events.video': 'Video',
    'events.videoDesc': 'Aufzeichnung des Laufs',
    'events.livestream': 'Livestream',
    'events.livestreamDesc': 'Live übertragener Lauf',
    'events.uploadSuccess': 'Datei erfolgreich hochgeladen',
    'events.uploadError': 'Fehler beim Hochladen der Datei',
    'events.fileTooBig': 'Datei zu groß (max. 100MB)',
    'events.invalidFileType': 'Ungültiger Dateityp',
    'events.requiredField': 'Dieses Feld ist erforderlich',
    'events.invalidTimeFormat': 'Ungültiges Zeitformat',
    'events.mediaUrlRequired': 'Media URL ist erforderlich für diesen Nachweistyp',
    'events.livestreamUrlRequired': 'Livestream URL ist erforderlich für Livestream-Nachweis',
    
    // Minigames
    'minigames.title': 'Minispiele',
    'minigames.play': 'Spielen',
    'minigames.highScore': 'Höchste Punktzahl',
    'minigames.difficulty': 'Schwierigkeit',
    'minigames.category': 'Kategorie',
    'minigames.allCategories': 'Alle Kategorien',
    'minigames.puzzle': 'Rätsel',
    'minigames.skill': 'Geschicklichkeit',
    'minigames.quiz': 'Quiz',
    'minigames.easy': 'Einfach',
    'minigames.medium': 'Mittel',
    'minigames.hard': 'Schwer',
    'minigames.players': 'Spieler',
    'minigames.player': 'Spieler',
    'minigames.comingSoon': 'Demnächst verfügbar',
    'minigames.notAvailable': 'Nicht verfügbar',
    'minigames.gameOver': 'Spiel beendet',
    'minigames.newHighScore': 'Neue Bestzeit!',
    'minigames.yourScore': 'Deine Punktzahl',
    'minigames.bestScore': 'Beste Punktzahl',
    'minigames.totalScore': 'Gesamtpunktzahl',
    'minigames.playAgain': 'Nochmal spielen',
    'minigames.backToMenu': 'Zurück zum Menü',
    'minigames.instructions': 'Anleitung',
    'minigames.startGame': 'Spiel starten',
    'minigames.pauseGame': 'Spiel pausieren',
    'minigames.resumeGame': 'Spiel fortsetzen',
    'minigames.quitGame': 'Spiel beenden',
    
    // Forum
    'forum.title': 'Community Forum',
    'forum.categories': 'Kategorien',
    'forum.threads': 'Threads',
    'forum.posts': 'Beiträge',
    'forum.newThread': 'Neuer Thread',
    'forum.reply': 'Antworten',
    'forum.author': 'Autor',
    'forum.lastPost': 'Letzter Beitrag',
    'forum.loading': 'Forum wird geladen...',
    'forum.discussWithCommunity': 'Diskutiere mit der Battle64-Community über N64-Spiele, Events und mehr',
    'forum.communityNexus': 'Community Nexus',
    'forum.activeUsers': 'Aktive Benutzer',
    'forum.totalUsers': 'Benutzer insgesamt',
    'forum.mostActive': 'Aktivste Kategorie',
    'forum.recentActivity': 'Letzte Aktivität',
    'forum.viewCategory': 'Kategorie anzeigen',
    'forum.noThreads': 'Keine Threads in dieser Kategorie',
    'forum.createFirstThread': 'Erstelle den ersten Thread!',
    
    // Community
    'community.title': 'Community',
    'community.members': 'Mitglieder',
    'community.onlineNow': 'Jetzt online',
    'community.recentlyJoined': 'Kürzlich beigetreten',
    'community.topPlayers': 'Top-Spieler',
    'community.viewProfile': 'Profil anzeigen',
    'community.sendMessage': 'Nachricht senden',
    'community.addFriend': 'Freund hinzufügen',
    'community.memberSince': 'Mitglied seit',
    'community.lastSeen': 'Zuletzt gesehen',
    'community.achievements': 'Erfolge',
    'community.gamesPlayed': 'Gespielte Spiele',
    'community.totalScore': 'Gesamtpunktzahl',
    
    // Leaderboard
    'leaderboard.title': 'Bestenliste',
    'leaderboard.rank': 'Rang',
    'leaderboard.player': 'Spieler',
    'leaderboard.score': 'Punkte',
    'leaderboard.level': 'Level',
    'leaderboard.weekly': 'Wöchentlich',
    'leaderboard.monthly': 'Monatlich',
    'leaderboard.allTime': 'Alle Zeiten',
    'leaderboard.topPlayers': 'Top-Spieler',
    'leaderboard.yourRank': 'Dein Rang',
    'leaderboard.notRanked': 'Nicht gerankt',
    'leaderboard.points': 'Punkte',
    'leaderboard.wins': 'Siege',
    'leaderboard.gamesPlayed': 'Gespielte Spiele',
    
    // Error Messages
    'error.generic': 'Ein Fehler ist aufgetreten',
    'error.networkError': 'Netzwerkfehler',
    'error.notFound': 'Seite nicht gefunden',
    'error.unauthorized': 'Nicht autorisiert',
    'error.forbidden': 'Zugriff verweigert',
    'error.serverError': 'Serverfehler',
    'error.tryAgain': 'Bitte versuche es erneut',
    'error.goHome': 'Zur Startseite',
    'error.contactSupport': 'Support kontaktieren',
    'error.somethingWentWrong': 'Etwas ist schief gelaufen',
    'error.technicalDetails': 'Technische Details',
    'error.reloadPage': 'Seite neu laden',
    
    // Success Messages
    'success.saved': 'Erfolgreich gespeichert',
    'success.updated': 'Erfolgreich aktualisiert',
    'success.deleted': 'Erfolgreich gelöscht',
    'success.submitted': 'Erfolgreich eingereicht',
    'success.joined': 'Erfolgreich beigetreten',
    'success.left': 'Erfolgreich verlassen',
    
    // Time and Date
    'time.seconds': 'Sekunden',
    'time.minutes': 'Minuten',
    'time.hours': 'Stunden',
    'time.days': 'Tage',
    'time.weeks': 'Wochen',
    'time.months': 'Monate',
    'time.years': 'Jahre',
    'time.ago': 'vor',
    'time.remaining': 'verbleibend',
    'time.now': 'jetzt',
    'time.today': 'heute',
    'time.yesterday': 'gestern',
    'time.tomorrow': 'morgen',
    
    // Language selector
    'language.german': 'Deutsch',
    'language.english': 'Englisch',
    'language.french': 'Französisch',
    'language.italian': 'Italienisch',
    'language.spanish': 'Spanisch',
    'language.greek': 'Griechisch',
    'language.turkish': 'Türkisch',
    'language.chinese': 'Chinesisch',
    'language.japanese': 'Japanisch',
    'language.russian': 'Russisch',
    'language.portuguese': 'Portugiesisch',
    'language.hindi': 'Hindi',
    'language.arabic': 'Arabisch',
    
    // Media and Documentation
    'media.screenshot': 'Screenshot',
    'media.video': 'Video',
    'media.livestream': 'Livestream',
    'media.photo': 'Foto',
    'media.notAvailable': 'Nicht verfügbar',
    'media.loading': 'Wird geladen...',
    'media.error': 'Fehler beim Laden',
    'media.play': 'Abspielen',
    'media.pause': 'Pausieren',
    'media.mute': 'Stumm',
    'media.unmute': 'Ton ein',
    'media.fullscreen': 'Vollbild',
    'media.exitFullscreen': 'Vollbild verlassen'
  },
  
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.quiz': 'Quiz',
    'nav.leaderboard': 'Leaderboard',
    'nav.profile': 'Profile',
    'nav.minigames': 'Minigames',
    'nav.events': 'Events',
    'nav.speedrun': 'Speedrun Media',
    'nav.collector': 'Collector Mode',
    'nav.forum': 'Forum',
    'nav.classic': 'Classic',
    'nav.marketplace': 'Marketplace',
    'nav.friends': 'Friends',
    'nav.fanart': 'Fan Art',
    'nav.news': 'News',
    'nav.media': 'Media',
    'nav.community': 'Community',
    
    // Home Screen
    'home.subtitle': 'The N64 Community for Millennials',
    'home.welcome': 'Welcome back',
    'home.quiz.subtitle': 'N64 Knowledge',
    'home.events.subtitle': 'Tournaments',
    'home.media.subtitle': 'Speedruns',
    'home.collector.subtitle': 'Collection',
    'home.forum.subtitle': 'Community',
    'home.profile.subtitle': 'My Account',
    'home.leaderboard.subtitle': 'Top Players',
    'home.minigames.subtitle': 'Fun',
    'home.marketplace.subtitle': 'Trading',
    'home.friends.subtitle': 'Social Network',
    'home.fanart.subtitle': 'Creativity',
    'home.news.subtitle': 'Updates',
    'home.classic.subtitle': 'Retro Experience',
    'home.footer.retro': 'Retro Reimagined',
    'home.footer.n64': 'For the N64 Generation',
    'home.footer.classic': 'Go to Classic View with News Feed',
    'home.footer.tagline': 'Battle64 - Where Nostalgia Meets Community',
    'home.newsfeed': 'News Feed',
    'home.liveEvents': 'Live Events',
    'home.noEventsActive': 'No active events',
    'home.noTimesSubmitted': 'No times submitted yet',
    'home.beTheFirst': 'Be the first!',
    'home.topLeaderboard': 'Top 3 Leaderboard:',
    'home.winner': 'Winner',
    'home.verified': 'Verified',
    'home.participants': 'Participants',
    'home.timeRemaining': 'Time remaining',
    'home.ended': 'Ended',
    'home.screenshot': 'Screenshot',
    'home.video': 'Video (Loop)',
    'home.livestream': 'Livestream',
    'home.livestreamProof': 'Livestream Proof',
    'home.noMediaAvailable': 'No media available',
    'home.showMoreNews': 'more news',
    
    // Common
    'common.welcome': 'Welcome',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.close': 'Close',
    'common.play': 'Play',
    'common.pause': 'Pause',
    'common.refresh': 'Refresh',
    'common.details': 'Details',
    'common.viewAll': 'View All',
    'common.noData': 'No data available',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.retry': 'Retry',
    
    // Authentication
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.email': 'Email',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.loginRequired': 'Login Required',
    'auth.loginRequiredMessage': 'You must be logged in to view this page.',
    'auth.loginRequiredForEvents': 'Please log in to participate in events!',
    
    // Quiz
    'quiz.title': 'N64 Quiz',
    'quiz.start': 'Start Quiz',
    'quiz.question': 'Question',
    'quiz.score': 'Score',
    'quiz.timeLeft': 'Time Left',
    'quiz.correct': 'Correct!',
    'quiz.incorrect': 'Incorrect!',
    'quiz.finished': 'Quiz Finished',
    'quiz.results': 'Results',
    'quiz.testYourKnowledge': 'Test your N64 knowledge!',
    'quiz.difficulty': 'Difficulty',
    'quiz.category': 'Category',
    'quiz.restart': 'Restart',
    'quiz.wrong': 'Wrong!',
    
    // Profile
    'profile.title': 'Profile',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.level': 'Level',
    'profile.experience': 'Experience',
    'profile.achievements': 'Achievements',
    'profile.statistics': 'Statistics',
    'profile.points': 'Points',
    'profile.badges': 'Badges',
    'profile.stats': 'Stats',
    'profile.games': 'Games',
    'profile.completed': 'Completed',
    'profile.favorites': 'Favorites',
    'profile.edit': 'Edit Profile',
    'profile.settings': 'Settings',
    'profile.overview': 'Overview',
    'profile.collection': 'Collection',
    'profile.records': 'Records',
    'profile.joinDate': 'Member since',
    'profile.editProfile': 'Edit Profile',
    'profile.personalBest': 'Personal Best',
    'profile.completions': 'Completions',
    'profile.bestTime': 'Best Time',
    'profile.highScore': 'High Score',
    'profile.achievedOn': 'Achieved on',
    
    // Events
    'events.title': 'Events',
    'events.upcoming': 'Upcoming Events',
    'events.active': 'Active Events',
    'events.completed': 'Completed Events',
    'events.participate': 'Participate',
    'events.details': 'Details',
    'events.noActive': 'No active events',
    'events.viewAll': 'View all events',
    'events.joinEvent': 'Join Event',
    'events.leaveEvent': 'Leave Event',
    'events.submitTime': 'Submit Time',
    'events.viewLeaderboard': 'View Leaderboard',
    'events.participants': 'Participants',
    'events.timeRemaining': 'Time Remaining',
    'events.ended': 'Ended',
    'events.notStarted': 'Not Started',
    'events.raceTime': 'Race Time',
    'events.documentation': 'Documentation',
    'events.mediaUrl': 'Media URL',
    'events.livestreamUrl': 'Livestream URL',
    'events.notes': 'Notes',
    'events.submissionSuccess': 'Time submitted successfully!',
    'events.joinSuccess': 'Successfully joined event! You can now submit your time.',
    'events.timeFormat': 'Format: MM:SS.mmm (e.g. 1:32.456)',
    'events.mediaFormatHelp': 'Accepted formats: JPG, PNG, MP4, WebM',
    'events.livestreamFormatHelp': 'Link to your Twitch or YouTube stream',
    'events.notesPlaceholder': 'Setup, controller, special circumstances...',
    'events.mediaUrlPlaceholder': 'https://twitch.tv/your-channel or https://youtube.com/watch?v=...',
    'events.raceSubmission': 'Submit Time',
    'events.eventTitle': 'Event Title',
    'events.selectDocumentation': 'Select Documentation',
    'events.photo': 'Photo',
    'events.photoDesc': 'Screenshot of final result',
    'events.video': 'Video',
    'events.videoDesc': 'Recording of the run',
    'events.livestream': 'Livestream',
    'events.livestreamDesc': 'Live streamed run',
    'events.uploadSuccess': 'File uploaded successfully',
    'events.uploadError': 'Error uploading file',
    'events.fileTooBig': 'File too large (max 100MB)',
    'events.invalidFileType': 'Invalid file type',
    'events.requiredField': 'This field is required',
    'events.invalidTimeFormat': 'Invalid time format',
    'events.mediaUrlRequired': 'Media URL is required for this documentation type',
    'events.livestreamUrlRequired': 'Livestream URL is required for livestream documentation',
    
    // Minigames
    'minigames.title': 'Minigames',
    'minigames.play': 'Play',
    'minigames.highScore': 'High Score',
    'minigames.difficulty': 'Difficulty',
    'minigames.category': 'Category',
    'minigames.allCategories': 'All Categories',
    'minigames.puzzle': 'Puzzle',
    'minigames.skill': 'Skill',
    'minigames.quiz': 'Quiz',
    'minigames.easy': 'Easy',
    'minigames.medium': 'Medium',
    'minigames.hard': 'Hard',
    'minigames.players': 'Players',
    'minigames.player': 'Player',
    'minigames.comingSoon': 'Coming Soon',
    'minigames.notAvailable': 'Not Available',
    'minigames.gameOver': 'Game Over',
    'minigames.newHighScore': 'New High Score!',
    'minigames.yourScore': 'Your Score',
    'minigames.bestScore': 'Best Score',
    'minigames.totalScore': 'Total Score',
    'minigames.playAgain': 'Play Again',
    'minigames.backToMenu': 'Back to Menu',
    'minigames.instructions': 'Instructions',
    'minigames.startGame': 'Start Game',
    'minigames.pauseGame': 'Pause Game',
    'minigames.resumeGame': 'Resume Game',
    'minigames.quitGame': 'Quit Game',
    
    // Forum
    'forum.title': 'Community Forum',
    'forum.categories': 'Categories',
    'forum.threads': 'Threads',
    'forum.posts': 'Posts',
    'forum.newThread': 'New Thread',
    'forum.reply': 'Reply',
    'forum.author': 'Author',
    'forum.lastPost': 'Last Post',
    'forum.loading': 'Loading forum...',
    'forum.discussWithCommunity': 'Discuss with the Battle64 community about N64 games, events and more',
    'forum.communityNexus': 'Community Nexus',
    'forum.activeUsers': 'Active Users',
    'forum.totalUsers': 'Total Users',
    'forum.mostActive': 'Most Active',
    'forum.recentActivity': 'Recent Activity',
    'forum.viewCategory': 'View Category',
    'forum.noThreads': 'No threads in this category',
    'forum.createFirstThread': 'Create the first thread!',
    
    // Community
    'community.title': 'Community',
    'community.members': 'Members',
    'community.onlineNow': 'Online Now',
    'community.recentlyJoined': 'Recently Joined',
    'community.topPlayers': 'Top Players',
    'community.viewProfile': 'View Profile',
    'community.sendMessage': 'Send Message',
    'community.addFriend': 'Add Friend',
    'community.memberSince': 'Member since',
    'community.lastSeen': 'Last seen',
    'community.achievements': 'Achievements',
    'community.gamesPlayed': 'Games Played',
    'community.totalScore': 'Total Score',
    
    // Leaderboard
    'leaderboard.title': 'Leaderboard',
    'leaderboard.rank': 'Rank',
    'leaderboard.player': 'Player',
    'leaderboard.score': 'Score',
    'leaderboard.level': 'Level',
    'leaderboard.weekly': 'Weekly',
    'leaderboard.monthly': 'Monthly',
    'leaderboard.allTime': 'All Time',
    'leaderboard.topPlayers': 'Top Players',
    'leaderboard.yourRank': 'Your Rank',
    'leaderboard.notRanked': 'Not Ranked',
    'leaderboard.points': 'Points',
    'leaderboard.wins': 'Wins',
    'leaderboard.gamesPlayed': 'Games Played',
    
    // Error Messages
    'error.generic': 'An error occurred',
    'error.networkError': 'Network error',
    'error.notFound': 'Page not found',
    'error.unauthorized': 'Unauthorized',
    'error.forbidden': 'Access denied',
    'error.serverError': 'Server error',
    'error.tryAgain': 'Please try again',
    'error.goHome': 'Go to Home',
    'error.contactSupport': 'Contact Support',
    'error.somethingWentWrong': 'Something went wrong',
    'error.technicalDetails': 'Technical Details',
    'error.reloadPage': 'Reload Page',
    
    // Success Messages
    'success.saved': 'Successfully saved',
    'success.updated': 'Successfully updated',
    'success.deleted': 'Successfully deleted',
    'success.submitted': 'Successfully submitted',
    'success.joined': 'Successfully joined',
    'success.left': 'Successfully left',
    
    // Time and Date
    'time.seconds': 'seconds',
    'time.minutes': 'minutes',
    'time.hours': 'hours',
    'time.days': 'days',
    'time.weeks': 'weeks',
    'time.months': 'months',
    'time.years': 'years',
    'time.ago': 'ago',
    'time.remaining': 'remaining',
    'time.now': 'now',
    'time.today': 'today',
    'time.yesterday': 'yesterday',
    'time.tomorrow': 'tomorrow',
    
    // Language selector
    'language.german': 'German',
    'language.english': 'English',
    'language.french': 'French',
    'language.italian': 'Italian',
    'language.spanish': 'Spanish',
    'language.greek': 'Greek',
    'language.turkish': 'Turkish',
    'language.chinese': 'Chinese',
    'language.japanese': 'Japanese',
    'language.russian': 'Russian',
    'language.portuguese': 'Portuguese',
    'language.hindi': 'Hindi',
    'language.arabic': 'Arabic',
    
    // Media and Documentation
    'media.screenshot': 'Screenshot',
    'media.video': 'Video',
    'media.livestream': 'Livestream',
    'media.photo': 'Photo',
    'media.notAvailable': 'Not Available',
    'media.loading': 'Loading...',
    'media.error': 'Error loading',
    'media.play': 'Play',
    'media.pause': 'Pause',
    'media.mute': 'Mute',
    'media.unmute': 'Unmute',
    'media.fullscreen': 'Fullscreen',
    'media.exitFullscreen': 'Exit Fullscreen'
  },
  
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.quiz': 'Quiz',
    'nav.leaderboard': 'Classement',
    'nav.profile': 'Profil',
    'nav.minigames': 'Mini-jeux',
    'nav.events': 'Événements',
    'nav.speedrun': 'Speedrun Media',
    'nav.collector': 'Mode Collectionneur',
    'nav.forum': 'Forum',
    'nav.classic': 'Classique',
    'nav.marketplace': 'Place de Marché',
    'nav.friends': 'Amis',
    'nav.fanart': 'Art de Fan',
    'nav.news': 'Actualités',
    'nav.media': 'Médias',
    'nav.community': 'Communauté',
    
    // Home Screen
    'home.subtitle': 'La Communauté N64 pour les Millennials',
    'home.welcome': 'Bon retour',
    'home.quiz.subtitle': 'Connaissances N64',
    'home.events.subtitle': 'Tournois',
    'home.media.subtitle': 'Speedruns',
    'home.collector.subtitle': 'Collection',
    'home.forum.subtitle': 'Communauté',
    'home.profile.subtitle': 'Mon Compte',
    'home.leaderboard.subtitle': 'Meilleurs Joueurs',
    'home.minigames.subtitle': 'Amusement',
    'home.marketplace.subtitle': 'Commerce',
    'home.friends.subtitle': 'Réseau social',
    'home.fanart.subtitle': 'Créativité',
    'home.news.subtitle': 'Mises à jour',
    'home.classic.subtitle': 'Expérience rétro',
    'home.footer.retro': 'Rétro Réinventé',
    'home.footer.n64': 'Pour la Génération N64',
    'home.footer.classic': 'Aller à la Vue Classique avec Flux d\'Actualités',
    'home.footer.tagline': 'Battle64 - Où la Nostalgie Rencontre la Communauté',
    'home.newsfeed': 'Flux d\'actualités',
    'home.liveEvents': 'Événements en direct',
    'home.noEventsActive': 'Aucun événement actif',
    'home.noTimesSubmitted': 'Aucun temps soumis',
    'home.beTheFirst': 'Soyez le premier !',
    'home.topLeaderboard': 'Top 3 du classement :',
    'home.winner': 'Gagnant',
    'home.verified': 'Vérifié',
    'home.participants': 'Participants',
    'home.timeRemaining': 'Temps restant',
    'home.ended': 'Terminé',
    'home.screenshot': 'Capture d\'écran',
    'home.video': 'Vidéo (boucle)',
    'home.livestream': 'Livestream',
    'home.livestreamProof': 'Preuve livestream',
    'home.noMediaAvailable': 'Aucun média disponible',
    'home.showMoreNews': 'actualités supplémentaires',
    
    // Common
    'common.welcome': 'Bienvenue',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.save': 'Sauvegarder',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.submit': 'Soumettre',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.close': 'Fermer',
    'common.play': 'Jouer',
    'common.pause': 'Pause',
    'common.refresh': 'Actualiser',
    'common.details': 'Détails',
    'common.viewAll': 'Voir tout',
    'common.noData': 'Aucune donnée disponible',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.ok': 'OK',
    'common.retry': 'Réessayer',
    
    // Authentication
    'auth.login': 'Connexion',
    'auth.logout': 'Déconnexion',
    'auth.register': 'S\'inscrire',
    'auth.username': 'Nom d\'utilisateur',
    'auth.password': 'Mot de passe',
    'auth.email': 'Email',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.loginRequired': 'Connexion requise',
    'auth.loginRequiredMessage': 'Vous devez être connecté pour voir cette page.',
    'auth.loginRequiredForEvents': 'Veuillez vous connecter pour participer aux événements !',
    
    // Quiz
    'quiz.title': 'Quiz N64',
    'quiz.start': 'Commencer le Quiz',
    'quiz.question': 'Question',
    'quiz.score': 'Score',
    'quiz.timeLeft': 'Temps Restant',
    'quiz.correct': 'Correct !',
    'quiz.incorrect': 'Incorrect !',
    'quiz.finished': 'Quiz Terminé',
    'quiz.results': 'Résultats',
    'quiz.testYourKnowledge': 'Testez vos connaissances N64 !',
    'quiz.difficulty': 'Difficulté',
    'quiz.category': 'Catégorie',
    'quiz.restart': 'Recommencer',
    'quiz.wrong': 'Faux !',
    
    // Profile
    'profile.title': 'Profil',
    'profile.username': "Nom d'utilisateur",
    'profile.email': 'Email',
    'profile.level': 'Niveau',
    'profile.experience': 'Expérience',
    'profile.achievements': 'Succès',
    'profile.statistics': 'Statistiques',
    'profile.points': 'Points',
    'profile.badges': 'Badges',
    'profile.stats': 'Stats',
    'profile.games': 'Jeux',
    'profile.completed': 'Terminé',
    'profile.favorites': 'Favoris',
    'profile.edit': 'Modifier le profil',
    'profile.settings': 'Paramètres',
    'profile.overview': 'Aperçu',
    'profile.collection': 'Collection',
    'profile.records': 'Records',
    'profile.joinDate': 'Membre depuis',
    'profile.editProfile': 'Modifier le profil',
    'profile.personalBest': 'Meilleur personnel',
    'profile.completions': 'Achèvements',
    'profile.bestTime': 'Meilleur temps',
    'profile.highScore': 'Meilleur score',
    'profile.achievedOn': 'Obtenu le',
    
    // Events
    'events.title': 'Événements',
    'events.upcoming': 'Événements à Venir',
    'events.active': 'Événements Actifs',
    'events.completed': 'Événements Terminés',
    'events.participate': 'Participer',
    'events.details': 'Détails',
    'events.noActive': 'Aucun événement actif',
    'events.viewAll': 'Voir tous les événements',
    'events.joinEvent': 'Rejoindre l\'événement',
    'events.leaveEvent': 'Quitter l\'événement',
    'events.submitTime': 'Soumettre le temps',
    'events.viewLeaderboard': 'Voir le classement',
    'events.participants': 'Participants',
    'events.timeRemaining': 'Temps restant',
    'events.ended': 'Terminé',
    'events.notStarted': 'Pas encore commencé',
    'events.raceTime': 'Temps de course',
    'events.documentation': 'Documentation',
    'events.mediaUrl': 'URL média',
    'events.livestreamUrl': 'URL livestream',
    'events.notes': 'Notes',
    'events.submissionSuccess': 'Temps soumis avec succès !',
    'events.joinSuccess': 'Rejoint l\'événement avec succès ! Vous pouvez maintenant soumettre votre temps.',
    'events.timeFormat': 'Format : MM:SS.mmm (ex. 1:32.456)',
    'events.mediaFormatHelp': 'Formats acceptés : JPG, PNG, MP4, WebM',
    'events.livestreamFormatHelp': 'Lien vers votre stream Twitch ou YouTube',
    'events.notesPlaceholder': 'Configuration, manette, circonstances particulières...',
    'events.mediaUrlPlaceholder': 'https://twitch.tv/votre-chaine ou https://youtube.com/watch?v=...',
    'events.raceSubmission': 'Soumettre le temps',
    'events.eventTitle': 'Titre de l\'événement',
    'events.selectDocumentation': 'Sélectionner la documentation',
    'events.photo': 'Photo',
    'events.photoDesc': 'Capture d\'écran du résultat final',
    'events.video': 'Vidéo',
    'events.videoDesc': 'Enregistrement de la course',
    'events.livestream': 'Livestream',
    'events.livestreamDesc': 'Course diffusée en direct',
    'events.uploadSuccess': 'Fichier téléchargé avec succès',
    'events.uploadError': 'Erreur lors du téléchargement du fichier',
    'events.fileTooBig': 'Fichier trop volumineux (max 100MB)',
    'events.invalidFileType': 'Type de fichier invalide',
    'events.requiredField': 'Ce champ est requis',
    'events.invalidTimeFormat': 'Format de temps invalide',
    'events.mediaUrlRequired': 'URL média requis pour ce type de documentation',
    'events.livestreamUrlRequired': 'URL livestream requis pour la documentation livestream',
    
    // Minigames
    'minigames.title': 'Mini-jeux',
    'minigames.play': 'Jouer',
    'minigames.highScore': 'Meilleur score',
    'minigames.difficulty': 'Difficulté',
    'minigames.category': 'Catégorie',
    'minigames.allCategories': 'Toutes les catégories',
    'minigames.puzzle': 'Puzzle',
    'minigames.skill': 'Adresse',
    'minigames.quiz': 'Quiz',
    'minigames.easy': 'Facile',
    'minigames.medium': 'Moyen',
    'minigames.hard': 'Difficile',
    'minigames.players': 'Joueurs',
    'minigames.player': 'Joueur',
    'minigames.comingSoon': 'Bientôt disponible',
    'minigames.notAvailable': 'Non disponible',
    'minigames.gameOver': 'Jeu terminé',
    'minigames.newHighScore': 'Nouveau record !',
    'minigames.yourScore': 'Votre score',
    'minigames.bestScore': 'Meilleur score',
    'minigames.totalScore': 'Score total',
    'minigames.playAgain': 'Rejouer',
    'minigames.backToMenu': 'Retour au menu',
    'minigames.instructions': 'Instructions',
    'minigames.startGame': 'Commencer le jeu',
    'minigames.pauseGame': 'Mettre en pause',
    'minigames.resumeGame': 'Reprendre le jeu',
    'minigames.quitGame': 'Quitter le jeu',
    
    // Forum
    'forum.title': 'Forum Communautaire',
    'forum.categories': 'Catégories',
    'forum.threads': 'Fils',
    'forum.posts': 'Messages',
    'forum.newThread': 'Nouveau Fil',
    'forum.reply': 'Répondre',
    'forum.author': 'Auteur',
    'forum.lastPost': 'Dernier Message',
    'forum.loading': 'Chargement du forum...',
    'forum.discussWithCommunity': 'Discutez avec la communauté Battle64 des jeux N64, événements et plus',
    'forum.communityNexus': 'Nexus communautaire',
    'forum.activeUsers': 'Utilisateurs actifs',
    'forum.totalUsers': 'Total des utilisateurs',
    'forum.mostActive': 'Plus actif',
    'forum.recentActivity': 'Activité récente',
    'forum.viewCategory': 'Voir la catégorie',
    'forum.noThreads': 'Aucun sujet dans cette catégorie',
    'forum.createFirstThread': 'Créez le premier sujet !',
    
    // Community
    'community.title': 'Communauté',
    'community.members': 'Membres',
    'community.onlineNow': 'En ligne maintenant',
    'community.recentlyJoined': 'Récemment rejoint',
    'community.topPlayers': 'Meilleurs joueurs',
    'community.viewProfile': 'Voir le profil',
    'community.sendMessage': 'Envoyer un message',
    'community.addFriend': 'Ajouter un ami',
    'community.memberSince': 'Membre depuis',
    'community.lastSeen': 'Vu pour la dernière fois',
    'community.achievements': 'Succès',
    'community.gamesPlayed': 'Jeux joués',
    'community.totalScore': 'Score total',
    
    // Leaderboard
    'leaderboard.title': 'Classement',
    'leaderboard.rank': 'Rang',
    'leaderboard.player': 'Joueur',
    'leaderboard.score': 'Score',
    'leaderboard.level': 'Niveau',
    'leaderboard.weekly': 'Hebdomadaire',
    'leaderboard.monthly': 'Mensuel',
    'leaderboard.allTime': 'Tous les temps',
    'leaderboard.topPlayers': 'Meilleurs joueurs',
    'leaderboard.yourRank': 'Votre rang',
    'leaderboard.notRanked': 'Non classé',
    'leaderboard.points': 'Points',
    'leaderboard.wins': 'Victoires',
    'leaderboard.gamesPlayed': 'Jeux joués',
    
    // Error Messages
    'error.generic': 'Une erreur s\'est produite',
    'error.networkError': 'Erreur réseau',
    'error.notFound': 'Page non trouvée',
    'error.unauthorized': 'Non autorisé',
    'error.forbidden': 'Accès refusé',
    'error.serverError': 'Erreur serveur',
    'error.tryAgain': 'Veuillez réessayer',
    'error.goHome': 'Aller à l\'accueil',
    'error.contactSupport': 'Contacter le support',
    'error.somethingWentWrong': 'Quelque chose s\'est mal passé',
    'error.technicalDetails': 'Détails techniques',
    'error.reloadPage': 'Recharger la page',
    
    // Success Messages
    'success.saved': 'Sauvegardé avec succès',
    'success.updated': 'Mis à jour avec succès',
    'success.deleted': 'Supprimé avec succès',
    'success.submitted': 'Soumis avec succès',
    'success.joined': 'Rejoint avec succès',
    'success.left': 'Quitté avec succès',
    
    // Time and Date
    'time.seconds': 'secondes',
    'time.minutes': 'minutes',
    'time.hours': 'heures',
    'time.days': 'jours',
    'time.weeks': 'semaines',
    'time.months': 'mois',
    'time.years': 'années',
    'time.ago': 'il y a',
    'time.remaining': 'restant',
    'time.now': 'maintenant',
    'time.today': 'aujourd\'hui',
    'time.yesterday': 'hier',
    'time.tomorrow': 'demain',
    
    // Language selector
    'language.german': 'Allemand',
    'language.english': 'Anglais',
    'language.french': 'Français',
    'language.italian': 'Italien',
    'language.spanish': 'Espagnol',
    'language.greek': 'Grec',
    'language.turkish': 'Turc',
    'language.chinese': 'Chinois',
    'language.japanese': 'Japonais',
    'language.russian': 'Russe',
    'language.portuguese': 'Portugais',
    'language.hindi': 'Hindi',
    'language.arabic': 'Arabe',
    
    // Media and Documentation
    'media.screenshot': 'Capture d\'écran',
    'media.video': 'Vidéo',
    'media.livestream': 'Livestream',
    'media.photo': 'Photo',
    'media.notAvailable': 'Non disponible',
    'media.loading': 'Chargement...',
    'media.error': 'Erreur de chargement',
    'media.play': 'Lire',
    'media.pause': 'Pause',
    'media.mute': 'Muet',
    'media.unmute': 'Activer le son',
    'media.fullscreen': 'Plein écran',
    'media.exitFullscreen': 'Quitter le plein écran'
  },

  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.quiz': 'Quiz',
    'nav.leaderboard': 'Classifica',
    'nav.profile': 'Profilo',
    'nav.minigames': 'Minigiochi',
    'nav.events': 'Eventi',
    'nav.speedrun': 'Speedrun Media',
    'nav.collector': 'Modalità Collezionista',
    'nav.forum': 'Forum',
    'nav.classic': 'Classico',
    'nav.marketplace': 'Mercato',
    'nav.friends': 'Amici',
    'nav.fanart': 'Fanart',
    'nav.news': 'Notizie',
    'nav.media': 'Media',
    
    // Home Screen
    'home.subtitle': 'La Comunità N64 per i Millennials',
    'home.welcome': 'Bentornato',
    'home.quiz.subtitle': 'Conoscenza N64',
    'home.events.subtitle': 'Tornei',
    'home.media.subtitle': 'Speedrun',
    'home.collector.subtitle': 'Collezione',
    'home.forum.subtitle': 'Comunità',
    'home.profile.subtitle': 'Il Mio Account',
    'home.leaderboard.subtitle': 'Migliori Giocatori',
    'home.minigames.subtitle': 'Divertimento',
    'home.footer.retro': 'Retro Reinventato',
    'home.footer.n64': 'Per la Generazione N64',
    'home.footer.classic': 'Alla vista classica con feed notizie',
    'home.footer.tagline': 'Battle64 - Dove la Nostalgia incontra la Comunità',
    
    // Common
    'common.welcome': 'Benvenuto',
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.submit': 'Invia',
    'common.back': 'Indietro',
    'common.next': 'Avanti',
    'common.previous': 'Precedente',
    'common.search': 'Cerca',
    'common.filter': 'Filtro',
    'common.sort': 'Ordina',
    'common.close': 'Chiudi',
    
    // Quiz
    'quiz.title': 'Quiz N64',
    'quiz.start': 'Inizia Quiz',
    'quiz.question': 'Domanda',
    'quiz.score': 'Punteggio',
    'quiz.timeLeft': 'Tempo rimasto',
    'quiz.correct': 'Corretto!',
    'quiz.incorrect': 'Sbagliato!',
    'quiz.finished': 'Quiz completato',
    'quiz.results': 'Risultati',
    
    // Profile
    'profile.title': 'Profilo',
    'profile.username': 'Nome utente',
    'profile.email': 'Email',
    'profile.level': 'Livello',
    'profile.experience': 'Esperienza',
    'profile.achievements': 'Risultati',
    'profile.statistics': 'Statistiche',
    
    // Events
    'events.title': 'Eventi',
    'events.upcoming': 'Eventi in Arrivo',
    'events.active': 'Eventi Attivi',
    'events.completed': 'Eventi Completati',
    'events.participate': 'Partecipa',
    'events.details': 'Dettagli',
    'events.noActive': 'Nessun evento attivo',
    'events.viewAll': 'Vedi tutti gli eventi',
    
    // Forum
    'forum.title': 'Forum della Comunità',
    'forum.categories': 'Categorie',
    'forum.threads': 'Thread',
    'forum.posts': 'Post',
    'forum.newThread': 'Nuovo Thread',
    'forum.reply': 'Rispondi',
    'forum.author': 'Autore',
    'forum.lastPost': 'Ultimo Post',
    
    // Language selector
    'language.german': 'Tedesco',
    'language.english': 'Inglese',
    'language.french': 'Francese',
    'language.italian': 'Italiano',
    'language.spanish': 'Spagnolo',
    'language.greek': 'Greco',
    'language.turkish': 'Turco',
    'language.chinese': 'Cinese',
    'language.japanese': 'Giapponese',
    'language.russian': 'Russo',
    'language.portuguese': 'Portoghese'
  },

  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.quiz': 'Quiz',
    'nav.leaderboard': 'Clasificación',
    'nav.profile': 'Perfil',
    'nav.minigames': 'Minijuegos',
    'nav.events': 'Eventos',
    'nav.speedrun': 'Speedrun Media',
    'nav.collector': 'Modo Coleccionista',
    'nav.forum': 'Foro',
    'nav.classic': 'Clásico',
    'nav.marketplace': 'Mercado',
    'nav.friends': 'Amigos',
    'nav.fanart': 'Fanart',
    'nav.news': 'Noticias',
    'nav.media': 'Media',
    
    // Home Screen
    'home.subtitle': 'La Comunidad N64 para Millennials',
    'home.welcome': 'Bienvenido de vuelta',
    'home.quiz.subtitle': 'Conocimiento N64',
    'home.events.subtitle': 'Torneos',
    'home.media.subtitle': 'Speedruns',
    'home.collector.subtitle': 'Colección',
    'home.forum.subtitle': 'Comunidad',
    'home.profile.subtitle': 'Mi Cuenta',
    'home.leaderboard.subtitle': 'Mejores Jugadores',
    'home.minigames.subtitle': 'Diversión',
    'home.footer.retro': 'Retro Reinventado',
    'home.footer.n64': 'Para la Generación N64',
    'home.footer.classic': 'A la vista clásica con feed de noticias',
    'home.footer.tagline': 'Battle64 - Donde la Nostalgia se encuentra con la Comunidad',
    
    // Common
    'common.welcome': 'Bienvenido',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.submit': 'Enviar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.search': 'Buscar',
    'common.filter': 'Filtro',
    'common.sort': 'Ordenar',
    'common.close': 'Cerrar',
    
    // Quiz
    'quiz.title': 'Quiz N64',
    'quiz.start': 'Iniciar Quiz',
    'quiz.question': 'Pregunta',
    'quiz.score': 'Puntuación',
    'quiz.timeLeft': 'Tiempo restante',
    'quiz.correct': '¡Correcto!',
    'quiz.incorrect': '¡Incorrecto!',
    'quiz.finished': 'Quiz completado',
    'quiz.results': 'Resultados',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.username': 'Nombre de usuario',
    'profile.email': 'Email',
    'profile.level': 'Nivel',
    'profile.experience': 'Experiencia',
    'profile.achievements': 'Logros',
    'profile.statistics': 'Estadísticas',
    
    // Events
    'events.title': 'Eventos',
    'events.upcoming': 'Próximos Eventos',
    'events.active': 'Eventos Activos',
    'events.completed': 'Eventos Completados',
    'events.participate': 'Participar',
    'events.details': 'Detalles',
    'events.noActive': 'No hay eventos activos',
    'events.viewAll': 'Ver todos los eventos',
    
    // Forum
    'forum.title': 'Foro de la Comunidad',
    'forum.categories': 'Categorías',
    'forum.threads': 'Hilos',
    'forum.posts': 'Publicaciones',
    'forum.newThread': 'Nuevo Hilo',
    'forum.reply': 'Responder',
    'forum.author': 'Autor',
    'forum.lastPost': 'Última Publicación',
    
    // Language selector
    'language.german': 'Alemán',
    'language.english': 'Inglés',
    'language.french': 'Francés',
    'language.italian': 'Italiano',
    'language.spanish': 'Español',
    'language.greek': 'Griego',
    'language.turkish': 'Turco',
    'language.chinese': 'Chino',
    'language.japanese': 'Japonés',
    'language.russian': 'Ruso',
    'language.portuguese': 'Portugués'
  },

  el: {
    // Navigation
    'nav.home': 'Αρχική',
    'nav.quiz': 'Κουίζ',
    'nav.leaderboard': 'Κατάταξη',
    'nav.profile': 'Προφίλ',
    'nav.minigames': 'Μίνι Παιχνίδια',
    'nav.events': 'Εκδηλώσεις',
    'nav.speedrun': 'Speedrun Media',
    'nav.collector': 'Λειτουργία Συλλέκτη',
    'nav.forum': 'Φόρουμ',
    'nav.classic': 'Κλασικό',
    'nav.marketplace': 'Αγορά',
    'nav.friends': 'Φίλοι',
    'nav.fanart': 'Fanart',
    'nav.news': 'Νέα',
    'nav.media': 'Μέσα',
    
    // Home Screen
    'home.subtitle': 'Η Κοινότητα N64 για τους Millennials',
    'home.welcome': 'Καλώς ήρθες πίσω',
    'home.quiz.subtitle': 'Γνώση N64',
    'home.events.subtitle': 'Τουρνουά',
    'home.media.subtitle': 'Speedruns',
    'home.collector.subtitle': 'Συλλογή',
    'home.forum.subtitle': 'Κοινότητα',
    'home.profile.subtitle': 'Ο Λογαριασμός μου',
    'home.leaderboard.subtitle': 'Κορυφαίοι Παίκτες',
    'home.minigames.subtitle': 'Διασκέδαση',
    'home.footer.retro': 'Ρετρό Ανανεωμένο',
    'home.footer.n64': 'Για τη Γενιά N64',
    'home.footer.classic': 'Στην κλασική προβολή με ροή ειδήσεων',
    'home.footer.tagline': 'Battle64 - Όπου η Νοσταλγία συναντά την Κοινότητα',
    
    // Common
    'common.welcome': 'Καλώς ήρθες',
    'common.loading': 'Φόρτωση...',
    'common.error': 'Σφάλμα',
    'common.save': 'Αποθήκευση',
    'common.cancel': 'Ακύρωση',
    'common.delete': 'Διαγραφή',
    'common.edit': 'Επεξεργασία',
    'common.submit': 'Υποβολή',
    'common.back': 'Πίσω',
    'common.next': 'Επόμενο',
    'common.previous': 'Προηγούμενο',
    'common.search': 'Αναζήτηση',
    'common.filter': 'Φίλτρο',
    'common.sort': 'Ταξινόμηση',
    'common.close': 'Κλείσιμο',
    
    // Quiz
    'quiz.title': 'Κουίζ N64',
    'quiz.start': 'Έναρξη Κουίζ',
    'quiz.question': 'Ερώτηση',
    'quiz.score': 'Σκορ',
    'quiz.timeLeft': 'Χρόνος που απομένει',
    'quiz.correct': 'Σωστό!',
    'quiz.incorrect': 'Λάθος!',
    'quiz.finished': 'Το κουίζ ολοκληρώθηκε',
    'quiz.results': 'Αποτελέσματα',
    
    // Profile
    'profile.title': 'Προφίλ',
    'profile.username': 'Όνομα χρήστη',
    'profile.email': 'Email',
    'profile.level': 'Επίπεδο',
    'profile.experience': 'Εμπειρία',
    'profile.achievements': 'Επιτεύγματα',
    'profile.statistics': 'Στατιστικά',
    
    // Events
    'events.title': 'Εκδηλώσεις',
    'events.upcoming': 'Επερχόμενες Εκδηλώσεις',
    'events.active': 'Ενεργές Εκδηλώσεις',
    'events.completed': 'Ολοκληρωμένες Εκδηλώσεις',
    'events.participate': 'Συμμετοχή',
    'events.details': 'Λεπτομέρειες',
    'events.noActive': 'Δεν υπάρχουν ενεργές εκδηλώσεις',
    'events.viewAll': 'Δες όλες τις εκδηλώσεις',
    
    // Forum
    'forum.title': 'Φόρουμ Κοινότητας',
    'forum.categories': 'Κατηγορίες',
    'forum.threads': 'Νήματα',
    'forum.posts': 'Αναρτήσεις',
    'forum.newThread': 'Νέο Νήμα',
    'forum.reply': 'Απάντηση',
    'forum.author': 'Συγγραφέας',
    'forum.lastPost': 'Τελευταία Ανάρτηση',
    
    // Language selector
    'language.german': 'Γερμανικά',
    'language.english': 'Αγγλικά',
    'language.french': 'Γαλλικά',
    'language.italian': 'Ιταλικά',
    'language.spanish': 'Ισπανικά',
    'language.greek': 'Ελληνικά',
    'language.turkish': 'Τουρκικά',
    'language.chinese': 'Κινεζικά',
    'language.japanese': 'Ιαπωνικά',
    'language.russian': 'Ρωσικά',
    'language.portuguese': 'Πορτογαλικά'
  },

  tr: {
    // Navigation
    'nav.home': 'Ana Sayfa',
    'nav.quiz': 'Quiz',
    'nav.leaderboard': 'Lider Tablosu',
    'nav.profile': 'Profil',
    'nav.minigames': 'Mini Oyunlar',
    'nav.events': 'Etkinlikler',
    'nav.speedrun': 'Speedrun Media',
    'nav.collector': 'Koleksiyoncu Modu',
    'nav.forum': 'Forum',
    'nav.classic': 'Klasik',
    'nav.marketplace': 'Pazar',
    'nav.friends': 'Arkadaşlar',
    'nav.fanart': 'Fanart',
    'nav.news': 'Haberler',
    'nav.media': 'Medya',
    
    // Home Screen
    'home.subtitle': 'Millennials için N64 Topluluğu',
    'home.welcome': 'Tekrar hoş geldin',
    'home.quiz.subtitle': 'N64 Bilgisi',
    'home.events.subtitle': 'Turnuvalar',
    'home.media.subtitle': 'Speedrunlar',
    'home.collector.subtitle': 'Koleksiyon',
    'home.forum.subtitle': 'Topluluk',
    'home.profile.subtitle': 'Hesabım',
    'home.leaderboard.subtitle': 'En İyi Oyuncular',
    'home.minigames.subtitle': 'Eğlence',
    'home.footer.retro': 'Retro Yeniden Keşfedildi',
    'home.footer.n64': 'N64 Nesli İçin',
    'home.footer.classic': 'Haber akışıyla klasik görünüme',
    'home.footer.tagline': 'Battle64 - Nostalji ile Topluluğun Buluştuğu Yer',
    
    // Common
    'common.welcome': 'Hoş geldin',
    'common.loading': 'Yükleniyor...',
    'common.error': 'Hata',
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.submit': 'Gönder',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.previous': 'Önceki',
    'common.search': 'Ara',
    'common.filter': 'Filtre',
    'common.sort': 'Sırala',
    'common.close': 'Kapat',
    
    // Quiz
    'quiz.title': 'N64 Quiz',
    'quiz.start': 'Quiz Başlat',
    'quiz.question': 'Soru',
    'quiz.score': 'Puan',
    'quiz.timeLeft': 'Kalan süre',
    'quiz.correct': 'Doğru!',
    'quiz.incorrect': 'Yanlış!',
    'quiz.finished': 'Quiz tamamlandı',
    'quiz.results': 'Sonuçlar',
    
    // Profile
    'profile.title': 'Profil',
    'profile.username': 'Kullanıcı adı',
    'profile.email': 'Email',
    'profile.level': 'Seviye',
    'profile.experience': 'Deneyim',
    'profile.achievements': 'Başarılar',
    'profile.statistics': 'İstatistikler',
    
    // Events
    'events.title': 'Etkinlikler',
    'events.upcoming': 'Yaklaşan Etkinlikler',
    'events.active': 'Aktif Etkinlikler',
    'events.completed': 'Tamamlanan Etkinlikler',
    'events.participate': 'Katıl',
    'events.details': 'Detaylar',
    'events.noActive': 'Aktif etkinlik yok',
    'events.viewAll': 'Tüm etkinlikleri görüntüle',
    
    // Forum
    'forum.title': 'Topluluk Forumu',
    'forum.categories': 'Kategoriler',
    'forum.threads': 'Konular',
    'forum.posts': 'Gönderiler',
    'forum.newThread': 'Yeni Konu',
    'forum.reply': 'Yanıtla',
    'forum.author': 'Yazar',
    'forum.lastPost': 'Son Gönderi',
    
    // Language selector
    'language.german': 'Almanca',
    'language.english': 'İngilizce',
    'language.french': 'Fransızca',
    'language.italian': 'İtalyanca',
    'language.spanish': 'İspanyolca',
    'language.greek': 'Yunanca',
    'language.turkish': 'Türkçe',
    'language.chinese': 'Çince',
    'language.japanese': 'Japonca',
    'language.russian': 'Rusça',
    'language.portuguese': 'Portekizce'
  },

  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.quiz': '测验',
    'nav.leaderboard': '排行榜',
    'nav.profile': '个人资料',
    'nav.minigames': '小游戏',
    'nav.events': '活动',
    'nav.speedrun': '速通媒体',
    'nav.collector': '收藏家模式',
    'nav.forum': '论坛',
    'nav.classic': '经典',
    'nav.marketplace': '市场',
    'nav.friends': '朋友',
    'nav.fanart': '粉丝艺术',
    'nav.news': '新闻',
    'nav.media': '媒体',
    
    // Home Screen
    'home.subtitle': '千禧一代的N64社区',
    'home.welcome': '欢迎回来',
    'home.quiz.subtitle': 'N64知识',
    'home.events.subtitle': '锦标赛',
    'home.media.subtitle': '速通',
    'home.collector.subtitle': '收藏',
    'home.forum.subtitle': '社区',
    'home.profile.subtitle': '我的账户',
    'home.leaderboard.subtitle': '顶级玩家',
    'home.minigames.subtitle': '娱乐',
    'home.footer.retro': '复古重塑',
    'home.footer.n64': '为N64一代',
    'home.footer.classic': '经典视图与新闻流',
    'home.footer.tagline': 'Battle64 - 怀旧与社区的交汇点',
    
    // Common
    'common.welcome': '欢迎',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.submit': '提交',
    'common.back': '返回',
    'common.next': '下一个',
    'common.previous': '上一个',
    'common.search': '搜索',
    'common.filter': '过滤',
    'common.sort': '排序',
    'common.close': '关闭',
    
    // Quiz
    'quiz.title': 'N64测验',
    'quiz.start': '开始测验',
    'quiz.question': '问题',
    'quiz.score': '分数',
    'quiz.timeLeft': '剩余时间',
    'quiz.correct': '正确！',
    'quiz.incorrect': '错误！',
    'quiz.finished': '测验完成',
    'quiz.results': '结果',
    
    // Profile
    'profile.title': '个人资料',
    'profile.username': '用户名',
    'profile.email': '邮箱',
    'profile.level': '等级',
    'profile.experience': '经验',
    'profile.achievements': '成就',
    'profile.statistics': '统计',
    
    // Events
    'events.title': '活动',
    'events.upcoming': '即将到来的活动',
    'events.active': '活跃活动',
    'events.completed': '已完成活动',
    'events.participate': '参与',
    'events.details': '详情',
    'events.noActive': '没有活跃的活动',
    'events.viewAll': '查看所有活动',
    
    // Forum
    'forum.title': '社区论坛',
    'forum.categories': '分类',
    'forum.threads': '主题',
    'forum.posts': '帖子',
    'forum.newThread': '新主题',
    'forum.reply': '回复',
    'forum.author': '作者',
    'forum.lastPost': '最后发帖',
    
    // Language selector
    'language.german': '德语',
    'language.english': '英语',
    'language.french': '法语',
    'language.italian': '意大利语',
    'language.spanish': '西班牙语',
    'language.greek': '希腊语',
    'language.turkish': '土耳其语',
    'language.chinese': '中文',
    'language.japanese': '日语',
    'language.russian': '俄语',
    'language.portuguese': '葡萄牙语'
  },

  ja: {
    // Navigation
    'nav.home': 'ホーム',
    'nav.quiz': 'クイズ',
    'nav.leaderboard': 'リーダーボード',
    'nav.profile': 'プロフィール',
    'nav.minigames': 'ミニゲーム',
    'nav.events': 'イベント',
    'nav.speedrun': 'スピードランメディア',
    'nav.collector': 'コレクターモード',
    'nav.forum': 'フォーラム',
    'nav.classic': 'クラシック',
    'nav.marketplace': 'マーケット',
    'nav.friends': '友達',
    'nav.fanart': 'ファンアート',
    'nav.news': 'ニュース',
    'nav.media': 'メディア',
    
    // Home Screen
    'home.subtitle': 'ミレニアル世代のN64コミュニティ',
    'home.welcome': 'お帰りなさい',
    'home.quiz.subtitle': 'N64知識',
    'home.events.subtitle': 'トーナメント',
    'home.media.subtitle': 'スピードラン',
    'home.collector.subtitle': 'コレクション',
    'home.forum.subtitle': 'コミュニティ',
    'home.profile.subtitle': 'マイアカウント',
    'home.leaderboard.subtitle': 'トッププレイヤー',
    'home.minigames.subtitle': '楽しみ',
    'home.footer.retro': 'レトロ再発明',
    'home.footer.n64': 'N64世代のために',
    'home.footer.classic': 'ニュースフィード付きクラシック表示へ',
    'home.footer.tagline': 'Battle64 - ノスタルジアとコミュニティの出会い',
    
    // Common
    'common.welcome': 'ようこそ',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.submit': '送信',
    'common.back': '戻る',
    'common.next': '次へ',
    'common.previous': '前へ',
    'common.search': '検索',
    'common.filter': 'フィルター',
    'common.sort': 'ソート',
    'common.close': '閉じる',
    
    // Quiz
    'quiz.title': 'N64クイズ',
    'quiz.start': 'クイズ開始',
    'quiz.question': '質問',
    'quiz.score': 'スコア',
    'quiz.timeLeft': '残り時間',
    'quiz.correct': '正解！',
    'quiz.incorrect': '不正解！',
    'quiz.finished': 'クイズ完了',
    'quiz.results': '結果',
    
    // Profile
    'profile.title': 'プロフィール',
    'profile.username': 'ユーザー名',
    'profile.email': 'メール',
    'profile.level': 'レベル',
    'profile.experience': '経験値',
    'profile.achievements': '実績',
    'profile.statistics': '統計',
    
    // Events
    'events.title': 'イベント',
    'events.upcoming': '予定イベント',
    'events.active': 'アクティブイベント',
    'events.completed': '完了イベント',
    'events.participate': '参加',
    'events.details': '詳細',
    'events.noActive': 'アクティブなイベントはありません',
    'events.viewAll': 'すべてのイベントを表示',
    
    // Forum
    'forum.title': 'コミュニティフォーラム',
    'forum.categories': 'カテゴリ',
    'forum.threads': 'スレッド',
    'forum.posts': '投稿',
    'forum.newThread': '新しいスレッド',
    'forum.reply': '返信',
    'forum.author': '作者',
    'forum.lastPost': '最後の投稿',
    
    // Language selector
    'language.german': 'ドイツ語',
    'language.english': '英語',
    'language.french': 'フランス語',
    'language.italian': 'イタリア語',
    'language.spanish': 'スペイン語',
    'language.greek': 'ギリシャ語',
    'language.turkish': 'トルコ語',
    'language.chinese': '中国語',
    'language.japanese': '日本語',
    'language.russian': 'ロシア語',
    'language.portuguese': 'ポルトガル語'
  },

  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.quiz': 'Викторина',
    'nav.leaderboard': 'Рейтинг',
    'nav.profile': 'Профиль',
    'nav.minigames': 'Мини-игры',
    'nav.events': 'События',
    'nav.speedrun': 'Спидран Медиа',
    'nav.collector': 'Режим коллекционера',
    'nav.forum': 'Форум',
    'nav.classic': 'Классика',
    'nav.marketplace': 'Торговая площадка',
    'nav.friends': 'Друзья',
    'nav.fanart': 'Фан-арт',
    'nav.news': 'Новости',
    'nav.media': 'Медиа',
    
    // Home Screen
    'home.subtitle': 'N64 сообщество для миллениалов',
    'home.welcome': 'Добро пожаловать',
    'home.quiz.subtitle': 'Знания N64',
    'home.events.subtitle': 'Турниры',
    'home.media.subtitle': 'Спидраны',
    'home.collector.subtitle': 'Коллекция',
    'home.forum.subtitle': 'Сообщество',
    'home.marketplace.subtitle': 'Торговля',
    'home.friends.subtitle': 'Социальная сеть',
    'home.fanart.subtitle': 'Творчество',
    'home.news.subtitle': 'Обновления',
    'home.classic.subtitle': 'Ретро опыт',
    
    // Profile
    'profile.level': 'Уровень',
    'profile.points': 'Очки',
    'profile.achievements': 'Достижения',
    'profile.badges': 'Значки',
    'profile.stats': 'Статистика',
    'profile.games': 'Игры',
    'profile.completed': 'Завершено',
    'profile.favorites': 'Избранное',
    'profile.edit': 'Редактировать профиль',
    'profile.settings': 'Настройки',
    
    // Quiz
    'quiz.title': 'N64 Викторина',
    'quiz.question': 'Вопрос',
    'quiz.score': 'Счет',
    'quiz.timeLeft': 'Осталось времени',
    'quiz.correct': 'Правильно!',
    'quiz.wrong': 'Неправильно!',
    'quiz.finished': 'Викторина завершена',
    'quiz.restart': 'Начать заново',
    'quiz.difficulty': 'Сложность',
    'quiz.category': 'Категория',
    
    // Leaderboard
    'leaderboard.title': 'Рейтинг',
    'leaderboard.rank': 'Место',
    'leaderboard.player': 'Игрок',
    'leaderboard.score': 'Счет',
    'leaderboard.level': 'Уровень',
    'leaderboard.weekly': 'За неделю',
    'leaderboard.monthly': 'За месяц',
    'leaderboard.allTime': 'За все время',
    
    // Minigames
    'minigames.title': 'Мини-игры',
    'minigames.play': 'Играть',
    'minigames.highScore': 'Лучший результат',
    'minigames.difficulty': 'Сложность',
    'minigames.category': 'Категория',
    
    // Events
    'events.title': 'События',
    'events.upcoming': 'Предстоящие события',
    'events.active': 'Активные события',
    'events.completed': 'Завершенные события',
    'events.participate': 'Участвовать',
    'events.details': 'Подробности',
    'events.noActive': 'Нет активных событий',
    'events.viewAll': 'Показать все события',
    
    // Forum
    'forum.title': 'Форум сообщества',
    'forum.categories': 'Категории',
    'forum.threads': 'Темы',
    'forum.posts': 'Сообщения',
    'forum.newThread': 'Новая тема',
    'forum.reply': 'Ответить',
    'forum.author': 'Автор',
    'forum.lastPost': 'Последнее сообщение',
    
    // Language selector
    'language.german': 'Немецкий',
    'language.english': 'Английский',
    'language.french': 'Французский',
    'language.italian': 'Итальянский',
    'language.spanish': 'Испанский',
    'language.greek': 'Греческий',
    'language.turkish': 'Турецкий',
    'language.chinese': 'Китайский',
    'language.japanese': 'Японский',
    'language.russian': 'Русский',
    'language.portuguese': 'Португальский'
  },

  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.quiz': 'Quiz',
    'nav.leaderboard': 'Classificação',
    'nav.profile': 'Perfil',
    'nav.minigames': 'Mini-jogos',
    'nav.events': 'Eventos',
    'nav.speedrun': 'Speedrun Mídia',
    'nav.collector': 'Modo Colecionador',
    'nav.forum': 'Fórum',
    'nav.classic': 'Clássico',
    'nav.marketplace': 'Mercado',
    'nav.friends': 'Amigos',
    'nav.fanart': 'Fan Art',
    'nav.news': 'Notícias',
    'nav.media': 'Mídia',
    
    // Home Screen
    'home.subtitle': 'A comunidade N64 para millennials',
    'home.welcome': 'Bem-vindo de volta',
    'home.quiz.subtitle': 'Conhecimento N64',
    'home.events.subtitle': 'Torneios',
    'home.media.subtitle': 'Speedruns',
    'home.collector.subtitle': 'Coleção',
    'home.forum.subtitle': 'Comunidade',
    'home.marketplace.subtitle': 'Comércio',
    'home.friends.subtitle': 'Rede social',
    'home.fanart.subtitle': 'Criatividade',
    'home.news.subtitle': 'Atualizações',
    'home.classic.subtitle': 'Experiência retrô',
    
    // Profile
    'profile.level': 'Nível',
    'profile.points': 'Pontos',
    'profile.achievements': 'Conquistas',
    'profile.badges': 'Distintivos',
    'profile.stats': 'Estatísticas',
    'profile.games': 'Jogos',
    'profile.completed': 'Concluído',
    'profile.favorites': 'Favoritos',
    'profile.edit': 'Editar perfil',
    'profile.settings': 'Configurações',
    
    // Quiz
    'quiz.title': 'Quiz N64',
    'quiz.question': 'Pergunta',
    'quiz.score': 'Pontuação',
    'quiz.timeLeft': 'Tempo restante',
    'quiz.correct': 'Correto!',
    'quiz.wrong': 'Errado!',
    'quiz.finished': 'Quiz terminado',
    'quiz.restart': 'Recomeçar',
    'quiz.difficulty': 'Dificuldade',
    'quiz.category': 'Categoria',
    
    // Leaderboard
    'leaderboard.title': 'Classificação',
    'leaderboard.rank': 'Posição',
    'leaderboard.player': 'Jogador',
    'leaderboard.score': 'Pontuação',
    'leaderboard.level': 'Nível',
    'leaderboard.weekly': 'Semanal',
    'leaderboard.monthly': 'Mensal',
    'leaderboard.allTime': 'Todos os tempos',
    
    // Minigames
    'minigames.title': 'Mini-jogos',
    'minigames.play': 'Jogar',
    'minigames.highScore': 'Melhor pontuação',
    'minigames.difficulty': 'Dificuldade',
    'minigames.category': 'Categoria',
    
    // Events
    'events.title': 'Eventos',
    'events.upcoming': 'Eventos próximos',
    'events.active': 'Eventos ativos',
    'events.completed': 'Eventos concluídos',
    'events.participate': 'Participar',
    'events.details': 'Detalhes',
    'events.noActive': 'Nenhum evento ativo',
    'events.viewAll': 'Ver todos os eventos',
    
    // Forum
    'forum.title': 'Fórum da comunidade',
    'forum.categories': 'Categorias',
    'forum.threads': 'Tópicos',
    'forum.posts': 'Postagens',
    'forum.newThread': 'Novo tópico',
    'forum.reply': 'Responder',
    'forum.author': 'Autor',
    'forum.lastPost': 'Última postagem',
    
    // Language selector
    'language.german': 'Alemão',
    'language.english': 'Inglês',
    'language.french': 'Francês',
    'language.italian': 'Italiano',
    'language.spanish': 'Espanhol',
    'language.greek': 'Grego',
    'language.turkish': 'Turco',
    'language.chinese': 'Chinês',
    'language.japanese': 'Japonês',
    'language.russian': 'Russo',
    'language.portuguese': 'Português',
    'language.hindi': 'हिन्दी',
    'language.arabic': 'العربية'
  },

  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.quiz': 'क्विज़',
    'nav.leaderboard': 'लीडरबोर्ड',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.minigames': 'मिनी गेम्स',
    'nav.events': 'इवेंट्स',
    'nav.speedrun': 'स्पीडरन मीडिया',
    'nav.collector': 'कलेक्टर मोड',
    'nav.forum': 'फोरम',
    'nav.classic': 'क्लासिक',
    'nav.marketplace': 'मार्केटप्लेस',
    'nav.friends': 'दोस्त',
    'nav.fanart': 'फैन आर्ट',
    'nav.news': 'न्यूज़',
    'nav.media': 'मीडिया',
    'nav.community': 'कम्युनिटी',
    
    // Home Screen
    'home.subtitle': 'मिलेनियल्स के लिए N64 कम्युनिटी',
    'home.welcome': 'वापस स्वागत है',
    'home.quiz.subtitle': 'N64 ज्ञान',
    'home.events.subtitle': 'टूर्नामेंट्स',
    'home.media.subtitle': 'स्पीडरन्स',
    'home.collector.subtitle': 'कलेक्शन',
    'home.forum.subtitle': 'कम्युनिटी',
    'home.profile.subtitle': 'मेरा अकाउंट',
    'home.leaderboard.subtitle': 'टॉप प्लेयर्स',
    'home.minigames.subtitle': 'मज़ा',
    'home.marketplace.subtitle': 'ट्रेडिंग',
    'home.friends.subtitle': 'सोशल नेटवर्क',
    'home.fanart.subtitle': 'रचनात्मकता',
    'home.news.subtitle': 'अपडेट्स',
    'home.classic.subtitle': 'रेट्रो अनुभव',
    'home.footer.retro': 'रेट्रो रीइमैजिंड',
    'home.footer.n64': 'N64 जेनेरेशन के लिए',
    'home.footer.classic': 'न्यूज़ फीड के साथ क्लासिक व्यू पर जाएं',
    'home.footer.tagline': 'Battle64 - जहाँ नॉस्टेल्जिया कम्युनिटी से मिलती है',
    'home.newsfeed': 'न्यूज़ फीड',
    'home.liveEvents': 'लाइव इवेंट्स',
    'home.noEventsActive': 'कोई सक्रिय इवेंट नहीं',
    'home.noTimesSubmitted': 'अभी तक कोई समय जमा नहीं किया गया',
    'home.beTheFirst': 'पहले बनें!',
    'home.topLeaderboard': 'टॉप 3 लीडरबोर्ड:',
    'home.winner': 'विजेता',
    'home.verified': 'सत्यापित',
    'home.participants': 'प्रतिभागी',
    'home.timeRemaining': 'समय शेष',
    'home.ended': 'समाप्त',
    'home.screenshot': 'स्क्रीनशॉट',
    'home.video': 'वीडियो (लूप)',
    'home.livestream': 'लाइवस्ट्रीम',
    'home.livestreamProof': 'लाइवस्ट्रीम प्रूफ',
    'home.noMediaAvailable': 'कोई मीडिया उपलब्ध नहीं',
    'home.showMoreNews': 'और समाचार',
    
    // Common
    'common.welcome': 'स्वागत है',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.save': 'सेव करें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'डिलीट करें',
    'common.edit': 'एडिट करें',
    'common.submit': 'सबमिट करें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.search': 'खोजें',
    'common.filter': 'फिल्टर',
    'common.sort': 'सॉर्ट करें',
    'common.close': 'बंद करें',
    'common.play': 'प्ले करें',
    'common.pause': 'रोकें',
    'common.refresh': 'रिफ्रेश करें',
    'common.details': 'विवरण',
    'common.viewAll': 'सभी देखें',
    'common.noData': 'कोई डेटा उपलब्ध नहीं',
    'common.confirm': 'पुष्टि करें',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.ok': 'ठीक है',
    'common.retry': 'पुनः प्रयास करें',
    
    // Authentication
    'auth.login': 'लॉगिन',
    'auth.logout': 'लॉगआउट',
    'auth.register': 'रजिस्टर करें',
    'auth.username': 'यूज़रनेम',
    'auth.password': 'पासवर्ड',
    'auth.email': 'ईमेल',
    'auth.confirmPassword': 'पासवर्ड कन्फर्म करें',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.loginRequired': 'लॉगिन आवश्यक',
    'auth.loginRequiredMessage': 'इस पेज को देखने के लिए आपको लॉगिन करना होगा।',
    'auth.loginRequiredForEvents': 'इवेंट्स में भाग लेने के लिए कृपया लॉगिन करें!',
    
    // Quiz
    'quiz.title': 'N64 क्विज़',
    'quiz.start': 'क्विज़ शुरू करें',
    'quiz.question': 'प्रश्न',
    'quiz.score': 'स्कोर',
    'quiz.timeLeft': 'समय शेष',
    'quiz.correct': 'सही!',
    'quiz.incorrect': 'गलत!',
    'quiz.finished': 'क्विज़ समाप्त',
    'quiz.results': 'परिणाम',
    'quiz.testYourKnowledge': 'अपना N64 ज्ञान परखें!',
    'quiz.difficulty': 'कठिनाई',
    'quiz.category': 'श्रेणी',
    'quiz.restart': 'फिर से शुरू करें',
    'quiz.wrong': 'गलत!',
    
    // Profile
    'profile.title': 'प्रोफ़ाइल',
    'profile.username': 'यूज़रनेम',
    'profile.email': 'ईमेल',
    'profile.level': 'लेवल',
    'profile.experience': 'अनुभव',
    'profile.achievements': 'उपलब्धियाँ',
    'profile.statistics': 'आंकड़े',
    'profile.points': 'पॉइंट्स',
    'profile.badges': 'बैज',
    'profile.stats': 'स्टेट्स',
    'profile.games': 'गेम्स',
    'profile.completed': 'पूर्ण',
    'profile.favorites': 'पसंदीदा',
    'profile.edit': 'प्रोफ़ाइल एडिट करें',
    'profile.settings': 'सेटिंग्स',
    'profile.overview': 'अवलोकन',
    'profile.collection': 'कलेक्शन',
    'profile.records': 'रिकॉर्ड्स',
    'profile.joinDate': 'सदस्य बने',
    'profile.editProfile': 'प्रोफ़ाइल एडिट करें',
    'profile.personalBest': 'व्यक्तिगत सर्वश्रेष्ठ',
    'profile.completions': 'पूर्णताएं',
    'profile.bestTime': 'सर्वश्रेष्ठ समय',
    'profile.highScore': 'उच्च स्कोर',
    'profile.achievedOn': 'प्राप्त किया',
    
    // Language selector
    'language.german': 'जर्मन',
    'language.english': 'अंग्रेजी',
    'language.french': 'फ्रेंच',
    'language.italian': 'इतालवी',
    'language.spanish': 'स्पेनिश',
    'language.greek': 'ग्रीक',
    'language.turkish': 'तुर्की',
    'language.chinese': 'चीनी',
    'language.japanese': 'जापानी',
    'language.russian': 'रूसी',
    'language.portuguese': 'पुर्तगाली',
    'language.hindi': 'हिन्दी',
    'language.arabic': 'अरबी'
  },

  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.quiz': 'اختبار',
    'nav.leaderboard': 'لوحة المتصدرين',
    'nav.profile': 'الملف الشخصي',
    'nav.minigames': 'ألعاب صغيرة',
    'nav.events': 'الأحداث',
    'nav.speedrun': 'وسائط الجري السريع',
    'nav.collector': 'وضع جامع',
    'nav.forum': 'منتدى',
    'nav.classic': 'كلاسيكي',
    'nav.marketplace': 'السوق',
    'nav.friends': 'الأصدقاء',
    'nav.fanart': 'فن المعجبين',
    'nav.news': 'الأخبار',
    'nav.media': 'الوسائط',
    'nav.community': 'المجتمع',
    
    // Home Screen
    'home.subtitle': 'مجتمع N64 لجيل الألفية',
    'home.welcome': 'مرحباً بعودتك',
    'home.quiz.subtitle': 'معرفة N64',
    'home.events.subtitle': 'البطولات',
    'home.media.subtitle': 'الجري السريع',
    'home.collector.subtitle': 'المجموعة',
    'home.forum.subtitle': 'المجتمع',
    'home.profile.subtitle': 'حسابي',
    'home.leaderboard.subtitle': 'أفضل اللاعبين',
    'home.minigames.subtitle': 'المتعة',
    'home.marketplace.subtitle': 'التداول',
    'home.friends.subtitle': 'الشبكة الاجتماعية',
    'home.fanart.subtitle': 'الإبداع',
    'home.news.subtitle': 'التحديثات',
    'home.classic.subtitle': 'التجربة الكلاسيكية',
    'home.footer.retro': 'إعادة تخيل الكلاسيكي',
    'home.footer.n64': 'لجيل N64',
    'home.footer.classic': 'اذهب إلى العرض الكلاسيكي مع تغذية الأخبار',
    'home.footer.tagline': 'Battle64 - حيث يلتقي الحنين بالمجتمع',
    'home.newsfeed': 'تغذية الأخبار',
    'home.liveEvents': 'الأحداث المباشرة',
    'home.noEventsActive': 'لا توجد أحداث نشطة',
    'home.noTimesSubmitted': 'لم يتم تقديم أي أوقات بعد',
    'home.beTheFirst': 'كن الأول!',
    'home.topLeaderboard': 'أفضل 3 في لوحة المتصدرين:',
    'home.winner': 'الفائز',
    'home.verified': 'موثق',
    'home.participants': 'المشاركون',
    'home.timeRemaining': 'الوقت المتبقي',
    'home.ended': 'انتهى',
    'home.screenshot': 'لقطة شاشة',
    'home.video': 'فيديو (حلقة)',
    'home.livestream': 'بث مباشر',
    'home.livestreamProof': 'إثبات البث المباشر',
    'home.noMediaAvailable': 'لا توجد وسائط متاحة',
    'home.showMoreNews': 'المزيد من الأخبار',
    
    // Common
    'common.welcome': 'مرحباً',
    'common.loading': 'جارٍ التحميل...',
    'common.error': 'خطأ',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.submit': 'إرسال',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.close': 'إغلاق',
    'common.play': 'تشغيل',
    'common.pause': 'إيقاف مؤقت',
    'common.refresh': 'تحديث',
    'common.details': 'التفاصيل',
    'common.viewAll': 'عرض الكل',
    'common.noData': 'لا توجد بيانات متاحة',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.ok': 'موافق',
    'common.retry': 'إعادة المحاولة',
    
    // Authentication
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.register': 'التسجيل',
    'auth.username': 'اسم المستخدم',
    'auth.password': 'كلمة المرور',
    'auth.email': 'البريد الإلكتروني',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.loginRequired': 'تسجيل الدخول مطلوب',
    'auth.loginRequiredMessage': 'يجب تسجيل الدخول لعرض هذه الصفحة.',
    'auth.loginRequiredForEvents': 'يرجى تسجيل الدخول للمشاركة في الأحداث!',
    
    // Quiz
    'quiz.title': 'اختبار N64',
    'quiz.start': 'بدء الاختبار',
    'quiz.question': 'سؤال',
    'quiz.score': 'النتيجة',
    'quiz.timeLeft': 'الوقت المتبقي',
    'quiz.correct': 'صحيح!',
    'quiz.incorrect': 'خطأ!',
    'quiz.finished': 'انتهى الاختبار',
    'quiz.results': 'النتائج',
    'quiz.testYourKnowledge': 'اختبر معرفتك بـ N64!',
    'quiz.difficulty': 'الصعوبة',
    'quiz.category': 'الفئة',
    'quiz.restart': 'إعادة البدء',
    'quiz.wrong': 'خطأ!',
    
    // Language selector
    'language.german': 'الألمانية',
    'language.english': 'الإنجليزية',
    'language.french': 'الفرنسية',
    'language.italian': 'الإيطالية',
    'language.spanish': 'الإسبانية',
    'language.greek': 'اليونانية',
    'language.turkish': 'التركية',
    'language.chinese': 'الصينية',
    'language.japanese': 'اليابانية',
    'language.russian': 'الروسية',
    'language.portuguese': 'البرتغالية',
    'language.hindi': 'الهندية',
    'language.arabic': 'العربية'
  }
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('de')

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language)
    // Store language preference in localStorage
    localStorage.setItem('n64-nexus-language', language)
  }

  // Translation function
  const t = (key: string): string => {
    const currentTranslations = translations[currentLanguage] as any
    const translation = currentTranslations?.[key]
    return translation || key
  }

  // Initialize language from localStorage on mount
  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('n64-nexus-language') as Language
    if (savedLanguage && ['de', 'en', 'fr', 'it', 'es', 'el', 'tr', 'zh', 'ja', 'ru', 'pt', 'hi', 'ar'].includes(savedLanguage)) {
      setCurrentLanguage(savedLanguage)
    }
  }, [])

  const value: LanguageContextType = {
    currentLanguage,
    setLanguage,
    t
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}